language: go
go:
  - 1.8.3
  - tip

os:
  - linux
  - osx

sudo: false

install:
  - go get -v ./...

script:
  - go vet
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
